modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/wujichen158/IkaKuji/issues"

[[mods]]
modId="ikakuji"
version="1.0.0"
displayName="IkaKuji"
displayURL="https://github.com/wujichen158/IkaKuji"
logoFile="icon.png"
credits="Thanks for developers"
authors="wujichen158"
description='''
Server-side only Kuji mod
'''

[[dependencies.ikakuji]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ikakuji]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"